import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";

type Props = { params: Promise<{ username: string }> };

export default async function PublicPortfolioPage({ params }: Props) {
  const { username } = await params;
  const supabase = await createClient();
  const { data: profile } = await supabase.from("portfolio_profiles").select("username,display_name,headline,bio,is_public").eq("username", username.toLowerCase()).eq("is_public", true).maybeSingle();
  if (!profile) notFound();
  const { data: items } = await supabase.from("portfolio_items").select("id,title,description,category,project_url,skills,created_at").eq("user_id", (await supabase.from("portfolio_profiles").select("user_id").eq("username", profile.username).eq("is_public", true).single()).data?.user_id ?? "00000000-0000-0000-0000-000000000000").eq("is_public", true).order("sort_order").order("created_at", { ascending: false });

  return <main className="public-portfolio"><nav><Link href="/">RUFFNECK LEARN</Link><span>LEARNER PORTFOLIO</span></nav><header><div className="avatar">{profile.display_name.trim().split(/\s+/).slice(0, 2).map((word: string) => word[0]?.toUpperCase()).join("") || "RL"}</div><p className="eyebrow">PUBLIC LEARNER PROFILE</p><h1>{profile.display_name}</h1>{profile.headline && <h2>{profile.headline}</h2>}{profile.bio && <p className="bio">{profile.bio}</p>}</header><section><div className="section-heading"><div><p className="eyebrow">SELECTED WORK</p><h2>Projects & achievements</h2></div><span>{items?.length ?? 0} entries</span></div>{!items?.length ? <div className="empty">This learner has not published any portfolio entries yet.</div> : <div className="items">{items.map((item: any) => <article key={item.id}><span className="chip">{item.category.replace("_", " ")}</span><h3>{item.title}</h3><p>{item.description}</p>{item.skills?.length > 0 && <div className="tags">{item.skills.map((skill: string) => <span key={skill}>{skill}</span>)}</div>}{item.project_url && <a href={item.project_url} target="_blank" rel="noreferrer">View project or verification ↗</a>}</article>)}</div>}</section><footer>Portfolio hosted by RuffNeck Learn · Shared by the learner</footer><style>{`
    .public-portfolio{max-width:1000px;margin:0 auto;padding:26px 22px 50px;color:#eaf2ff;min-height:100vh}.public-portfolio nav{display:flex;justify-content:space-between;gap:14px;color:#9bb0cc;font-size:11px;letter-spacing:.13em}.public-portfolio nav a{color:#83dff0;text-decoration:none;font-weight:900}.public-portfolio header{margin:30px 0 24px;padding:36px;border:1px solid #234565;border-radius:24px;background:radial-gradient(circle at 90% 0,#174a61 0,transparent 36%),linear-gradient(135deg,#0b1e3a,#102d4a)}.avatar{width:64px;height:64px;border-radius:18px;background:#00b4d8;color:#062039;display:grid;place-items:center;font-size:21px;font-weight:900;margin-bottom:22px}.eyebrow{font-size:10px;font-weight:900;letter-spacing:.16em;color:#57d4eb;margin:0 0 10px}.public-portfolio h1{font-size:clamp(32px,6vw,52px);letter-spacing:-.045em;line-height:1.06;margin:0 0 10px}.public-portfolio header h2{font-size:18px;color:#c9d9e9;font-weight:600;margin:0 0 14px}.bio{white-space:pre-wrap;max-width:720px;color:#aebfd4;line-height:1.8;margin:0}.section-heading{display:flex;justify-content:space-between;align-items:end;gap:12px;margin:30px 0 16px}.section-heading h2{font-size:25px;margin:0}.section-heading>span{font-size:12px;color:#a0b6ce}.items{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:15px}.items article{border:1px solid #25445f;border-radius:16px;padding:21px;background:#0d213b;min-width:0}.chip{display:inline-flex;padding:5px 8px;border-radius:999px;background:#143b50;color:#81e2f1;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.items h3{font-size:18px;margin:12px 0 8px}.items article p{white-space:pre-wrap;color:#b6c8dd;font-size:13px;line-height:1.75;overflow-wrap:anywhere}.tags{display:flex;flex-wrap:wrap;gap:6px;margin:13px 0}.tags span{border:1px solid #2a4662;color:#b9cbe0;padding:4px 7px;border-radius:6px;font-size:11px}.items article a{display:inline-block;color:#73d9ee;font-size:12px;text-decoration:none;margin-top:10px}.empty{padding:30px;text-align:center;border:1px dashed #31506b;border-radius:14px;color:#a5b8cf}.public-portfolio footer{margin-top:42px;border-top:1px solid #203b56;padding-top:20px;color:#8098b4;font-size:11px}@media(max-width:650px){.public-portfolio{padding:18px 14px 36px}.public-portfolio header{padding:25px 21px}.items{grid-template-columns:1fr}}
  `}</style></main>;
}
